{% set name = "mfusepy" %}
{% set version = "3.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33b5e13d1595c7acf0171fb30faaf1ce47df484457352b1d379a9e2b39ac3d3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - __linux

test:
  requires:
    - python {{ python_min }}
  imports:
    - mfusepy

about:
  home: https://github.com/mxmlnkn/mfusepy
  license: ISC
  license_file: LICENSE
  summary: Ctypes bindings for the high-level API in libfuse 2 and 3

extra:
  recipe-maintainers:
    - mxmlnkn
